# Generated by Django 4.0.6 on 2022-07-18 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=254)),
                ('type', models.CharField(choices=[('back-end', 'Backend'), ('front-end', 'Frontend'), ('iOS', 'Ios'), ('Android', 'Android')], max_length=30)),
                ('author_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=254)),
                ('tag', models.CharField(choices=[('BUG', 'Bug'), ('AMÉLIORATION', 'Amelioration'), ('TÂCHE', 'Tache')], max_length=30)),
                ('priority', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('ÉLEVÉE', 'Elevee')], max_length=30)),
                ('status', models.CharField(choices=[('À faire', 'A Faire'), ('En cours', 'En Cours'), ('Terminé', 'Termine')], max_length=30)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.users')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('author', 'Author'), ('contributor', 'Contributor'), ('visitor', 'Visitor')], max_length=30)),
                ('role', models.CharField(default='contributor', max_length=30)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projects')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('description', models.CharField(max_length=254)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.users')),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.issues')),
            ],
        ),
    ]
